env:
    global: 
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1
sudo: required
language: generic
services:
    - docker 

before_install:
    - docker build -t harishindalkar/docker-multi-container-aws -f ./client/Dockerfile.dev ./client
    
    

script:
    - docker run -e CI=true harishindalkar/docker-multi-container-aws npm run test

after_success:
    - docker build -t harishindalkar/multi-client  ./client
    - docker build -t harishindalkar/multi-worker  ./worker
    - docker build -t harishindalkar/multi-server ./server
    - docker build -t harishindalkar/multi-nginx ./nginx
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push harishindalkar/multi-client:latest
    - docker push harishindalkar/multi-worker:latest
    - docker push harishindalkar/multi-server:latest
    - docker push harishindalkar/multi-nginx:latest

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    env: MultiDocker-env
    app: multi-docker
    bucket_name: "elasticbeanstalk-us-east-2-067346712233"
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
