env:
    global: 
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1
sudo: required
language: generic
services:
    - docker 

before_install:
    - docker build -t harishindalkar/docker-multi-container-aws -f ./client/Dockerfile.dev ./client
    
    

script:
    - docker run -e CI=true harishindalkar/docker-multi-container-aws npm run test

after_success:
    - docker build -t harishindalkar/multi-client  ./client
    - docker build -t harishindalkar/multi-worker  ./worker
    - docker build -t harishindalkar/multi-server ./server
    - docker build -t harishindalkar/multi-nginx ./nginx
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
    # - echo "3$Hwolverineh" | docker login -u "harishindalkar" --password-stdin
    - docker push harishindalkar/multi-client
    - docker push harishindalkar/multi-worker
    - docker push harishindalkar/multi-server
    - docker push harishindalkar/multi-nginx
