version: '3'
services:
    postgres:
        image: 'postgres:10.5'
        # image: postgres:
        environment:
        #     # - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_PASSWORD=postgres_password
        restart: always
    redis:
        image: 'redis:latest'
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev 
            context: ./nginx 
        ports:
            - '4000:80'
    api:
        depends_on:
            - postgres 
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
            - PGHOST=postgres
        stdin_open: true
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        stdin_open: true 
    worker:
        build:
            dockerfile: Dockerfile.dev 
            context: ./worker 
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        stdin_open: true
